### PR TITLE
Prevent the same source from being added twice (Once for 'config', on…

### PR DESCRIPTION
**Pull request by AnthonyARM**
…ce for 'global')

I'm not too familiar with the code so I'm not sure how the plugin_cache is supposed to work
But at the moment add_source is called once for each iteration on line 105 which triggers an exception during the second iteration.
This seems to fix the problem but I don't understand the code well enough to say if that's the proper thing to do.

### CODE REVIEW

**Comment by setrofim** [comment]
Could you share your agenda/config? I have tried running multiple iterations however have not hit this issue.

**Comment by AnthonyARM** [comment]
Here is my agenda:

```yaml
config: {device: mate9, run_name: computer_vision_validation}
global: {iterations: 1}
workloads:
- name: computer_vision
  params: {border_mode: 2, data_directory: /data/data/home,
    display_output: false, image: 640x480, num_threads: 4, options: validate_neon
      validate_cl, suffix: '', tensors: true, working_subdirectory: antbar01}
- name: computer_vision
  params: {border_mode: 0, data_directory: /data/data/home,
    display_output: false, image: 640x480, num_threads: 4, options: validate_neon
      validate_cl, suffix: '', tensors: false, working_subdirectory: antbar01}
- name: computer_vision
  params: {border_mode: 0, data_directory: /data/data/home,
    display_output: false, image: '', num_threads: 4, options: validate_neon validate_cl,
    suffix: '', tensors: false, working_subdirectory: antbar01}
- name: computer_vision
  params: {border_mode: 1, data_directory: /data/data/home,
    display_output: false, image: opticalflow, num_threads: 4, options: old_new validate_neon
      validate_cl, suffix: '', tensors: false, working_subdirectory: antbar01}
```
I believe the problem happens if you both have a `config` and `global` section in your agenda

**Comment by setrofim** [comment]
I've submitted an alternative fix for this issue:

https://github.com/ARM-software/workload-automation/pull/424

**Comment by AnthonyARM** [comment]
Thanks !

**Pull request closed without merging**
