### PR TITLE
Fixed an error emptying the reading buffer of the poller

### PR DESCRIPTION
**Pull request by Pablololo12**
Fixed how the reading buffer was empty. Instead of buf[0] = '\0'; the correct way to avoid bad readings is memset(buf, 0, sizeof(buf));

### CODE REVIEW

**Comment by setrofim** [comment]
Please merge the two commits.

**Comment by Pablololo12** [comment]
Hi, I can't do that!

**Comment by setrofim** [comment]
Erm, why not?

**Comment by Pablololo12** [comment]
I don't have permits

**Comment by setrofim** [comment]
Sorry, I meant merge them together, i.e. squash them.

**Pull request closed without merging**
