### PR TITLE
Googleplaybooks: Updating workload to work with change in parameter types

### PR DESCRIPTION
**Pull request by scojac01**
Due to a change in the parameter kind we have to update the googleplaybooks workload to work with integers for page numbers as opposed to strings.

This was missed in the previous update. https://github.com/ARM-software/workload-automation/commit/8f1206678abd737fa49ab8643446b69c47b2b4ac

### CODE REVIEW

**Comment by setrofim** [comment]
Please could you update the commit description with the link to the commit that contains the changes it mentions. As it is now, it is not clear what is meant.

**Comment by setrofim** [comment]
Sorry, please could you add that to the commit message, *not* the pull request description.

**Comment by scojac01** [comment]
I updated the commit message but I seem to have added in a Facebook change and a merge from somewhere? I'm not really sure what's happened here :(

**Comment by setrofim** [comment]
remove the commits you don't want

**Pull request closed without merging**
