### PR TITLE
[RFC] instrumentation: Add initial Instrument for BayLibre ACME

### PR DESCRIPTION
**Pull request by bjackman**
I hacked this up hastily by copy-pasting from LISA. I have since heard that someone else was already working on this? If so we can throw this away.

Missing features:

1. Output format same as DAQ and ARM Energy Probe instruments
2. Allow specifying path to iio-capture
3. Proper doc/description strings

The main reason I'm posting this now is to discuss point 1. It looks like WA currently doesn't have a standardised format for energy measurements, rather each instrument uses its own. Is that something that will change in WA3, with devlib's richer `Instrument` API?

### CODE REVIEW

**Comment by bjackman** [comment]
Another thought - this probably works with anything that uses IIO. Probably still prefer to call this "ACME" rather than "IIO" though since I can't even name anoth

**Comment by bjackman** [comment]
Oops, accidentally closed

**Comment by setrofim** [comment]
> The main reason I'm posting this now is to discuss point 1. It looks like WA currently doesn't have a standardised format for energy measurements, rather each instrument uses its own. Is that something that will change in WA3, with devlib's richer Instrument API?

Yes, that is correct -- standardized output formant is something that was added in devlib, and sol will be in WA3; WA2 doesn't have that.

**Comment by setrofim** [comment]
FYI: created a  pull for the alternative implementation: https://github.com/ARM-software/workload-automation/pull/410

**Comment by bjackman** [comment]
Closing, prefer #410.

**Pull request closed without merging**
