### PR TITLE
fw/target/info: Allow for missing values when reading from pod

### PR DESCRIPTION
**Pull request by marcbonnici**
Allow for deserializing of a TargetInfo pod when missing information.

### CODE REVIEW

**Comment by setrofim** [comment]
Most of that information is not optional, so deserialisation *should* fail if it's missing.

**Comment by marcbonnici** [comment]
Updated to only allow for select missing information.

**Comment by setrofim** [comment]
I still don't understand why those values would be missing from a valid structure?

**Comment by marcbonnici** [comment]
These values have been added in sequentially so when trying to load results generated with an older versions of WA they can be missing and therefore cause deserialization to fail.

**Pull request closed without merging**
