### PR TITLE
instrumetnation: add support for BayLibre ACME cape

### PR DESCRIPTION
**Pull request by setrofim**
Add an instrument for collecting power and energy from BayLibre
ACME cape probe.

This is an alternative implementation to:
https://github.com/ARM-software/workload-automation/pull/407 and should be
reviewed in concert.

### CODE REVIEW

**Comment by setrofim** [comment]
> The other one supports multiple channels but it's not actually a super useful feature and the mechanism is a bit awkward. Could always modify this to add that feature later.

I did not add that because I currently have access to only one probe, so a) I would not be able to test it, and b) I'm not sure what would be the most useful way to expose that. Unless you already have an existing use case to support multiple iio devices, lets add support for that when there is one.

I've made changes to address the other comments.

**Comment by bjackman** [comment]
Sweet, this looks good to me FWIW and I'll let you know when I've tested it. Agree on the multi-channel thing.

**Comment by bjackman** [comment]
Oh, also typo "instrumetnation" in the commit msg

**Comment by setrofim** [comment]
fixed

**Comment by bjackman** [comment]
Tested seems good. One point - for my own use case I'd like this to be the last instrument started and the first stopped, regardless of the accuracy cost to other instruments. I suppose the only way to achieve that is the edit the code to make `start` `fast_start` right? Is `fast_start` supposed to represent that this instrument starts quickly or that it's high priority?

**Comment by setrofim** [comment]
>  I suppose the only way to achieve that is the edit the code to make start fast_start right?

That's the simplest way, yes. You can also manually register a method with a particular priority, e.g.
https://github.com/ARM-software/workload-automation/blob/master/wlauto/instrumentation/trace_cmd/__init__.py#L176. Which may be useful if you want a finer grained control over when something runs.

For this I'll just make them `very_fast`.

> Is fast_start supposed to represent that this instrument starts quickly or that it's high priority?

It means that the method is fast, and therefore will have smaller impact on instrumentation that is already running, and therefore WA will start it closer to the invocation of the workload i.e. if it's before the workload, e.g. start, it will be invoked later, and if it's after the workload, e.g. stop, it will be invoked sooner than the other callbacks for the same signal. Internally, this translates to a higher priority.

**Pull request merged**
